name: Secret Santa Deploy
on:
  push:
    branches:
      - secret_santa_actions
jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install pnpm
        run: npm install -g pnpm
      - name: Install packages
        run: pnpm install
      - name: Deploy
        run:
          pnpm run deploy